name: stocks  # You can change the environment name here
channels:
  - defaults
dependencies:
  - python>=3.12.0  # Specify the python version
  - numpy>=1.25.1
  - plotly>=5.0.0
  - matplotlib>=3.6.0
  - scipy>=1.9.0
  - pandas>2.0
  - streamlit=1.24.1
  - scikit-learn=1.2.0

  - pip  # Make sure pip is installed
  - pip:
    - numpy>=1.23.0
    - plotly>=5.0.0
    - matplotlib>=3.6.0
    - scipy>=1.9.0
    - pandas>=1.4.0
    - streamlit>=1.16.0